name: twitart_app
description: Twitart is an social application like Twitter using Firebase

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^4.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  ionicons: ^0.1.2
  lottie: ^1.3.0
  flutter_screenutil: ^5.5.3+2
  google_sign_in: ^5.4.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  flutter_native_splash: ^2.2.4
  timeago: ^3.2.2
  google_sign_in_mocks: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator:              
  build_runner:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/