// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQaLe_qME3tYBO28nJrlRQyba6dYR7c0s',
    appId: '1:762772338355:android:aaf489d52f89d1310de2c6',
    messagingSenderId: '762772338355',
    projectId: 'twitart-meetucup1998',
    storageBucket: 'twitart-meetucup1998.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVFqSEkYyfqDPpsPx4frItOyujfyV6xrY',
    appId: '1:762772338355:ios:661b6163a93edae50de2c6',
    messagingSenderId: '762772338355',
    projectId: 'twitart-meetucup1998',
    storageBucket: 'twitart-meetucup1998.appspot.com',
    androidClientId: '762772338355-ferdtmqoohcletp7fo5ndt7p8l48snr2.apps.googleusercontent.com',
    iosClientId: '762772338355-38iecag6klvg11k5c0073bv6que0qrmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitartApp',
  );
}
